import json
import logging
from typing import Dict, Any
import google.generativeai as genai
from app.core.config import settings
from app.feedback.diff_engine import compare_features

logger = logging.getLogger(__name__)

if settings.GEMINI_API_KEY:
    genai.configure(api_key=settings.GEMINI_API_KEY)

feedback_model = genai.GenerativeModel(settings.GEMINI_MODEL)


def get_subjective_feedback(original_md: str, edited_md: str) -> Dict[str, Any]:
    """
    Use Gemini ONLY for subjective metrics (tone, teaching style, clarity).
    """
    if not settings.GEMINI_API_KEY:
        return {}

    prompt = f"""
Compare these two versions of a note. The 'Original' was generated by an AI. The 'Edited' was modified by a user to fit their personal style.
Identify subjective shifts in tone, clarity, and teaching style. DO NOT analyze formatting (bullets, sentence lengths, etc).

Original:
{original_md[:5000]}

Edited:
{edited_md[:5000]}

Return a JSON object with this exact structure (only include fields that shifted significantly):
{{
    "changes": [
        {{
            "feature": "tone",
            "new": "more academic/casual/etc",
            "reason": "User changed informal phrases to formal definitions."
        }}
    ]
}}
"""
    try:
        response = feedback_model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json"
            ),
        )
        return json.loads(response.text)
    except Exception as e:
        logger.error(f"Error getting subjective feedback: {e}")
        return {"changes": []}


def generate_style_feedback(original_md: str, edited_md: str) -> Dict[str, Any]:
    """
    Combine deterministic structural feedback with subjective LLM feedback.
    """
    # 1. Deterministic structural diff
    structural_changes = compare_features(original_md, edited_md)

    # 2. Subjective Gemini diff
    subjective_data = get_subjective_feedback(original_md, edited_md)
    subjective_changes = subjective_data.get("changes", [])

    # Combine
    all_changes = structural_changes + subjective_changes
    return {"changes": all_changes}
