"""Simplify database

Revision ID: 3c78baad7199
Revises: 68d1092bfddd
Create Date: 2026-07-09 22:29:06.909996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c78baad7199"
down_revision: Union[str, None] = "68d1092bfddd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_tasks_id"), "background_tasks", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_evaluation_metrics_generated_note_id"), table_name="evaluation_metrics"
    )
    op.drop_index(op.f("ix_evaluation_metrics_id"), table_name="evaluation_metrics")
    op.drop_table("evaluation_metrics")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_metrics",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "generated_note_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "personalization_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "structural_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "formatting_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "section_order_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sentence_style_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "example_density_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "edit_distance_similarity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["generated_note_id"],
            ["generated_notes.id"],
            name=op.f("evaluation_metrics_generated_note_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("evaluation_metrics_pkey")),
    )
    op.create_index(
        op.f("ix_evaluation_metrics_id"), "evaluation_metrics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_metrics_generated_note_id"),
        "evaluation_metrics",
        ["generated_note_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_background_tasks_id"), table_name="background_tasks")
    op.drop_table("background_tasks")
    # ### end Alembic commands ###
