"""add style profile

Revision ID: 78bc778476bc
Revises: b0950cd55dce
Create Date: 2026-07-07 22:12:29.494609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78bc778476bc"
down_revision: Union[str, None] = "b0950cd55dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "style_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "profile_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_profiles_id"), "style_profiles", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_style_profiles_user_id"), "style_profiles", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_style_profiles_user_id"), table_name="style_profiles")
    op.drop_index(op.f("ix_style_profiles_id"), table_name="style_profiles")
    op.drop_table("style_profiles")
    # ### end Alembic commands ###
