"""add feedback models

Revision ID: bf9742e33f34
Revises: 78bc778476bc
Create Date: 2026-07-07 22:21:48.951777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf9742e33f34"
down_revision: Union[str, None] = "78bc778476bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "style_profile_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "profile_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_profile_versions_id"),
        "style_profile_versions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_style_profile_versions_user_id"),
        "style_profile_versions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "generated_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lecture_id", sa.Integer(), nullable=True),
        sa.Column("generated_markdown", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["lecture_id"],
            ["lectures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_notes_id"), "generated_notes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_generated_notes_user_id"), "generated_notes", ["user_id"], unique=False
    )
    op.create_table(
        "edited_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generated_note_id", sa.Integer(), nullable=False),
        sa.Column("edited_markdown", sa.String(), nullable=False),
        sa.Column(
            "edited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["generated_note_id"],
            ["generated_notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edited_notes_generated_note_id"),
        "edited_notes",
        ["generated_note_id"],
        unique=False,
    )
    op.create_index(op.f("ix_edited_notes_id"), "edited_notes", ["id"], unique=False)
    op.create_table(
        "style_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generated_note_id", sa.Integer(), nullable=False),
        sa.Column(
            "feedback_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["generated_note_id"],
            ["generated_notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_feedback_generated_note_id"),
        "style_feedback",
        ["generated_note_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_style_feedback_id"), "style_feedback", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_style_feedback_id"), table_name="style_feedback")
    op.drop_index(
        op.f("ix_style_feedback_generated_note_id"), table_name="style_feedback"
    )
    op.drop_table("style_feedback")
    op.drop_index(op.f("ix_edited_notes_id"), table_name="edited_notes")
    op.drop_index(op.f("ix_edited_notes_generated_note_id"), table_name="edited_notes")
    op.drop_table("edited_notes")
    op.drop_index(op.f("ix_generated_notes_user_id"), table_name="generated_notes")
    op.drop_index(op.f("ix_generated_notes_id"), table_name="generated_notes")
    op.drop_table("generated_notes")
    op.drop_index(
        op.f("ix_style_profile_versions_user_id"), table_name="style_profile_versions"
    )
    op.drop_index(
        op.f("ix_style_profile_versions_id"), table_name="style_profile_versions"
    )
    op.drop_table("style_profile_versions")
    # ### end Alembic commands ###
